CREATE TABLE livro(

	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	editora VARCHAR(50) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	publicacao DATE NOT NULL,
	resumo VARCHAR(50) NOT NULL,
	autor_id BIGINT(20) NOT NULL,
	FOREIGN KEY (autor_id) REFERENCES autor(id)

)ENGINE=InnoDB DEFAULT CHARSET=utf8;