CREATE TABLE comentario (

	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	data DATE NOT NULL,
	texto VARCHAR(200) NOT NULL,
	usuario VARCHAR(100) NOT NULL,
	livro_id BIGINT(20) NOT NULL,
	FOREIGN KEY (livro_id) REFERENCES livro(id)

)ENGINE=InnoDB DEFAULT CHARSET=utf8;